spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: user
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


springdoc:
  api-docs:
    path: /docs # 접속 path 설정
  swagger-ui:
    path: /swagger-ui # 접속 path 설정